### ISSUE TITLE
Clean linter warnings 

### ISSUE THREAD

**Issue by ahcorde** [ignitionrobotics/ign-rendering#105]
Running the following script generates many linter warnings

```bash
bash tools/code_check.sh
```

The idea of this issue is clean all these warnings

**Comment by chapulina** [comment]
That is running on CI and it's currently clear for all supported branches:

* https://build.osrfoundation.org/job/ignition_rendering-ci-ign-rendering2-bionic-amd64/
* https://build.osrfoundation.org/job/ignition_rendering-ci-ign-rendering3-bionic-amd64/
* https://build.osrfoundation.org/job/ignition_rendering-ci-master-bionic-amd64/

What happens often is that a different version of cppcheck will show different errors. So maybe this issue can be more explicit about which version we're trying to satisfy?

**Comment by chapulina** [comment]
`tools/code_check.sh` is deprecated in favour of `make codecheck`, which is being tested on CI and is currently clear for all supported branches.
