### ISSUE TITLE
[Ogre 2.x] DepthCamera integration test fails on macOS

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-rendering#108]
depth camera integration test (`INTEGRATION_depth_camera`) fails with ogre2 plugin on macOS.

error message from jenkins:

```
/Users/jenkins/workspace/ignition_rendering-ci-pr_any-homebrew-amd64/ign-rendering/test/integration/depth_camera.cc:247
Expected: (mb) > (0u), actual: 0 vs 0
```

ogre.log reveals some warnings when validating glsl shaders, see [gist](https://gist.github.com/iche033/5ae46ce69c38444c6c99e5bc274b73b4)

**Comment by darksylinc** [comment]
I think this is #332
