### ISSUE TITLE
Support decals

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-rendering#184]
The goal is to support adding visual decals on the surface of meshes, e.g. imagine industrial concrete flooring with some spill marks on them. These spill marks can be applied on top of the floor as decals.

2 approaches:

a) Proper decals:
Here's high level description and code snippet for ogre 1.x:
http://wiki.ogre3d.org/OgreDecal

We need to figure out how to do it for ogre 2.1

b) Overlay 
Create separate geometry → use texture with alpha transparency → overlay the geometry on top of another.
We need to set rendering order to avoid z-fighting

**Comment by ahcorde** [comment]
@iche033 can we consider this done ?  https://github.com/ignitionrobotics/ign-rendering/pull/188

**Comment by iche033** [comment]
yep done. 

Implemented approach b)
