### ISSUE TITLE
Thermal Camera - Inconsistent Background Behavior

### ISSUE THREAD

**Issue by adlarkin** [ignitionrobotics/ign-rendering#205]
Following the [thermal camera tutorial](https://github.com/ignitionrobotics/ign-sensors/blob/ign-sensors4/tutorials/thermal_camera.md) results in a different background appearance between the [ign-rendering3](https://github.com/ignitionrobotics/ign-rendering/tree/ign-rendering3) and [ign-rendering4](https://github.com/ignitionrobotics/ign-rendering/tree/ign-rendering4) branches.

Here's the result of running `ign gazebo thermal_camera.sdf` with `ign-rendering3`:
![rendering3](https://user-images.githubusercontent.com/42042756/105423935-6778bf80-5c14-11eb-8302-abd055760603.png)

Here's the result of running `ign gazebo thermal_camera.sdf` with `ign-rendering4`:
![rendering4](https://user-images.githubusercontent.com/42042756/105423946-6c3d7380-5c14-11eb-9e70-0d11cf71a809.png)

It appears that this behavior is caused by different visibility flags being assigned to non-temperature visuals. For example, if the following change is made to [Ogre2ThermalCamera.cc](https://github.com/ignitionrobotics/ign-rendering/blob/fdc39a312dc9f99c7c24f4a4b7297ae859906cca/ogre/src/OgreThermalCamera.cc), it shows that non-temperature visuals have a visibility flag of `0x3fffffff` in `ign-rendering4`, but are `0x0fffffff` in `ign-rendering3`:
```diff
diff --git a/ogre2/src/Ogre2ThermalCamera.cc b/ogre2/src/Ogre2ThermalCamera.cc
index 012e0f23..9fddf0ad 100644
--- a/ogre2/src/Ogre2ThermalCamera.cc
+++ b/ogre2/src/Ogre2ThermalCamera.cc
@@ -231,6 +231,11 @@ void Ogre2ThermalCameraMaterialSwitcher::preRenderTargetUpdate(
           }
         }
       }
+      else
+      {
+        ignerr << "non temp object, has the following visibility flags: " << std::hex
+          << item->getVisibilityFlags() << "\n";
+      }
     }
     itor.moveNext();
   }
```

Since the thermal camera's visibility flag is `0x10000000`, this means that the background (which doesn't have a temperature visual) is visible in `ign-rendering4`, but not in `ign-rendering3` (a visual can be seen by the thermal camera if the result of `AND`ing the visual's visibility flag with the thermal camera's visibility flag is a flag with non-zero bits).

**Comment by chapulina** [comment]
Addressed in https://github.com/ignitionrobotics/ign-rendering/pull/189
