### ISSUE TITLE
Add support for configuring intensity of lights

### ISSUE THREAD

**Issue by ahcorde** [ignitionrobotics/ign-rendering#232]
Add support for configuring intensity of lights

**Comment by ahcorde** [comment]
- [ ] sdformat  https://github.com/osrf/sdformat/pull/484
 - [ ] ign-msgs https://github.com/ignitionrobotics/ign-msgs/pull/131
 - [ ] ign-rendering https://github.com/ignitionrobotics/ign-rendering/pull/233
 - [ ] ign-gazebo https://github.com/ignitionrobotics/ign-gazebo/pull/612

**Comment by ahcorde** [comment]
Diferrent point light intensities:

 - Ogre1

![Selección_102](https://user-images.githubusercontent.com/1933907/106935307-7a62b800-671b-11eb-8520-49f5b4e02ec3.png)

 - Ogre2

![Selección_101](https://user-images.githubusercontent.com/1933907/106935312-7cc51200-671b-11eb-961c-674fe485fcf4.png)

**Comment by iche033** [comment]
can you add `SetIntensity(1.0)` to the [Reset](https://github.com/ignitionrobotics/ign-rendering/blob/272885cb7b08c67b84a9ffbb70cb577905f8b215/include/ignition/rendering/base/BaseLight.hh#L142) function?

**Comment by ahcorde** [comment]
All PR are merged. Closing.
