### ISSUE TITLE
Add gazebo msgs: Capsule and Cone

### ISSUE THREAD

**Issue by ahcorde** [ignitionrobotics/ign-rendering#293]
## Desired behavior

Related with this PR https://github.com/ignitionrobotics/ign-rendering/pull/289.

Capsule and Cone are defined in `ignition::msgs` but not in `gazebo::msgs` https://github.com/osrf/gazebo/tree/gazebo11/gazebo/msgs

The objective is to add these msgs to `ignition::gazebo` and uncomment the code in the PR.

**Comment by chapulina** [comment]
I don't think we can change the message definitions in Gazebo classic at this point, because it would break ABI. I don't think we should add capsule and ellipsoid support to Gazebo classic at this point.
