### ISSUE TITLE
DepthGaussianNoise integration test fails on some HW

### ISSUE THREAD

**Issue by darksylinc** [ignitionrobotics/ign-rendering#315]
I noticed DepthGaussianNoise fails on my machine but works fine in the CI server.

The integration fails:

```
[ RUN      ] GaussianNoise/RenderPassTest.DepthGaussianNoise/ogre2
/home/matias/Projects/ign/src/ign-rendering/test/integration/render_pass.cc:357: Failure
Expected equality of these values:
  255u
    Which is: 255
  ma
    Which is: 0
[  FAILED  ] GaussianNoise/RenderPassTest.DepthGaussianNoise/ogre2, where GetParam() = "ogre2" (12204 ms)
```

To be more specific the integration expects an alpha value (packed/encoded) of 255, but instead it's 0.

Upon closer examination, this is because the test uploads this colour texture:

![colourTexture](https://user-images.githubusercontent.com/3395130/116828936-31829a00-ab78-11eb-97ae-a2f0daa847f0.png)

However the texture is of format R8G8B8_SRGB, therefore GPUs are allowed to do whatever they want with the alpha value.

In the case of my AMD Radeon RX 560 2GB using Mesa drivers, it decides to fetch an alpha of 0 instead of 255, thus causing the test to fail.

This bug should fix itself in the Ogre 2.2 version, because Ogre 2.2 explicitly forbids the use of RGB888 textures in the GPU. The `PFG_RGB8_*` family of pixel formats can only be used for CPU operations.

## Environment
* OS Version: Xubuntu 18.04 LTS
* Source or binary build? https://github.com/ignitionrobotics/ign-rendering/commit/07c4ca96c924db4004ccab9e0b7a1e6ac5b1b033
    - Rendering plugin: ogre2
      - [x] running on real hardware
    - Rendering system info:
```
direct rendering: Yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 560 Series (POLARIS11, DRM 3.40.0, 5.11.0-051100-generic, LLVM 10.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.3 (git-663fa46287)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.3 (git-663fa46287)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.3 (git-663fa46287)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 550 640SP / RX 560/560X] [1002:67ff] (rev cf)

root      1680  1.4  0.5 2840064 165080 tty7   Ssl+ 18:35   0:27 /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
matias   11249  0.0  0.0  17988  1032 pts/2    S+   19:05   0:00 grep --color=auto Xorg
 ```

## Description

* Expected behavior: Test should pass
* Actual behavior: Test fails

## Steps to reproduce

1. Run ign/build/ignition-rendering5/bin/INTEGRATION_render_pass
2. Use AMD Radeon RX 560 2GB HW, Mesa drivers.

## Workaround

Run the test with LIBGL_ALWAYS_SOFTWARE=1

## Other

This bug is incredibly low priority for me; given that the CI does its job, I can comment out the failing lines involving alpha or workaround it with SW, and that it should fix itself with Ogre 2.2

**Comment by chapulina** [comment]
I may have closed https://github.com/ignitionrobotics/ign-rendering/issues/175 too soon. This test had been flaky on macOS CI.
