### ISSUE TITLE
[Ogre2.x] Not all lights cast shadows

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-rendering#34]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/issues/34)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
# Description 
shadow maps are limited to those defined in [PbsMaterials.compositor ](https://github.com/ignitionrobotics/ign-rendering/blob/master/ogre2/src/media/2.0/scripts/Compositors/PbsMaterials.compositor)

We need to add the ability to create more shadow maps for new lights added to the scene

# Steps to Reproduce
Add two spot lights.

**Expected behavior:**

Both lights should cast shadows

**Actual behavior:**

Only the spot light closest to the camera casts shadows

**Reproduces how often:**

all the time

# Versions
ogre2 in `gz11` branch

**Comment by iche033** [comment]
issue should already be fixed in ign-rendering2 / blueprint
