### ISSUE TITLE
Provide information about the Ogre version used at configure time

### ISSUE THREAD

**Issue by j-rivero** [ignitionrobotics/ign-rendering#375]
## Desired behavior

Not all the Ogre versions are officially supported in Ignition but most of them can be used to compile the software. It would be useful to provide users with information when they are not using the supported versions.

## Alternatives considered

At least a couple of approaches can be done:

1. Enable unsupported versions using a cmake flag. Fail the build if the versions is not one of the supported ones and implement a flag to enable the configuration to pass with others.

2. Warn users if the ogre version used is not the officially supported one but leave the configuration to finish.

## Implementation suggestion

Not to break people builds out there I think that the safer approach would be to go with 2.

## Additional context

See problems in https://github.com/ignitionrobotics/ign-rendering/issues/374

**Comment by chapulina** [comment]
See #376

**Comment by Blast545** [comment]
I think this can be closed, as #376 is merged.

**Comment by j-rivero** [comment]
> I think this can be closed, as #376 is merged.

Yup, gracias.
