### ISSUE TITLE
[Ogre1.x] Mesh material memory leak

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-rendering#39]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/issues/39)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
Each time a mesh (submesh) is created, a new default material is also created for the mesh. That new material is never deleted.

[related code](https://github.com/ignitionrobotics/ign-rendering/blob/4e356e58b7ab399c697a2d0180befc024be3f884/ogre/src/OgreMeshFactory.cc#L428:434)

**Comment by AndrejOrsula** [comment]
I believe this issue is already fixed and can be closed? (Unless there is another reason to keep it around)

**Comment by chapulina** [comment]
It looks like it has.
