### ISSUE TITLE
Ogre2 doesn't support transparency in <material> colors

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-rendering#47]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/issues/47)) by Addisu Z. Taddese (Bitbucket: [azeey](https://bitbucket.org/%7B9d7fdc68-d270-4080-bf03-4df0d0dbf635%7D/), GitHub: [azeey](https://github.com/azeey)).**

The original report had attachments: [test_transparency.sdf](https://osrf-migration.github.io/ignition-gh-pages/data/repositories/ignitionrobotics/ign-rendering/issues/47/attachments/test_transparency.sdf)

----------------------------------------
# Description 

The alpha value of colors in `<material>` tags seem to be ignored when using Ogre2.   

# Steps to Reproduce

1. Run the attached sdf in ign-gazebo
2. Change the `<engine>` to ogre and run in ign-gazebo.

**Expected behavior:**  
Alpha values to affect transparency. In the example, the red box should have a transparency of 0.5.

**Actual behavior:**

Transparency is not affected by alpha values

**Reproduces how often:** 

100 %

# Versions

All versions

**Comment by iche033** [comment]
implemented in https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/pull-requests/243/page/1
