### ISSUE TITLE
[Ogre2.x] Spot / Point light shines through objects

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-rendering#53]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/issues/53)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
# Description

Spot / point light shines through objects. Objects are lit even when they are fully occluded.

The same problems also happens when using ogre1.x.

# Step to reproduce

1. Put box A in front of a spot light
2. Put box B behind box A so that box A sits in between the spot light and box B.

## Expected behavior

Box B should not be lit

## Actual Behavior

Box B is lit by the spot light

## Reproduces how often

All the time

# Versions

all versions

**Comment by iche033** [comment]
more fixes done in [pull request #222](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/pull-requests/222)
