### ISSUE TITLE
GpuLidar skip depth image creation

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-rendering#75]
The GPU lidar in Ignition Rendering converts XYZ data to a depth image. Meanwhile, Ignition Sensors converts the depth image back to XYZ data when creating a point cloud message.

The back and forth conversion should be bypassed.

**Comment by iche033** [comment]
xyz data generation added in https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/pull-requests/187/page/1
