### ISSUE TITLE
Missing AxisVisual and ArrowVisual implementation

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-rendering#85]
Implementation of AxisVisual and ArrowVisual is missing for ogre ([empty classes](https://github.com/ignitionrobotics/ign-rendering/blob/master/ogre/src/OgreArrowVisual.cc)) and ogre2 ([no implementation](https://github.com/ignitionrobotics/ign-rendering/blob/master/ogre2/src/Ogre2Scene.cc#L282)).

**Comment by Levi-Armstrong** [comment]
These methods currently work for ogre1 and ogre2 on melodic so I looked into the issue. The class is empty because it is implemented in the base class (BaseAxisVisual and BaseArrowVisual) using calls to createConeVisual and createCylinderVisual.

**Comment by iche033** [comment]
oh I missed that. Thanks for looking into this. I think I just tested ogre2 at the time and it was not working. It's mainly missing a few hooks to return a valid pointer. Done in pull requests #87

**Comment by Levi-Armstrong** [comment]
Thank you for the support.

**Comment by iche033** [comment]
pull request #87
